### ISSUE TITLE
Actors

### ISSUE THREAD

**Issue by frknasir** [frknasir/kmdmc#4]
Two questions here for discussion...

- Who are going to use this system?
- How are they going to use it?

Is the Audit department under accounting?

### Accounting 
- Chief Accountant(Boss)
- Assistant Accountant
- ....

### Payroll
- HR

### Procurement
- Procurement Boss
- Maybe number 2???

### Estate/Revenue
???

### Project Management
???

### Budgeting
???

### Memo
???

**Comment by alanadamu** [comment]
I think it may be difficult to say beforehand what different types of people will use the system. Which is why a permissions based ACL will probably a good solution to this as we have discussed in the kaduna meeting. That gives us flexibility

**Comment by alanadamu** [comment]
But yes, what is most likely to happen is a situation whereby different departments have a boss and other users will less access. However this access can be not structured. So permissions can probably work

**Comment by frknasir** [comment]
> I think it may be difficult to say beforehand what different types of people will use the system. Which is why a permissions based ACL will probably a good solution to this as we have discussed in the kaduna meeting. That gives us flexibility

yeah it will be permission based. alright then...since we cant know before hand, im closing this issue.
